services:
  dev-db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - dev-network
      
networks:
  dev-network:
    driver: bridge

name: recipe_api